package com.codehackerr.simple.bdd;/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import org.junit.Test;
import org.junit.runner.RunWith;
import org.mockito.Mock;
import org.mockito.runners.MockitoJUnitRunner;

import static com.codehackerr.simple.bdd.GivenStep.given;
import static org.mockito.Mockito.verify;

@RunWith(MockitoJUnitRunner.class)
public class GivenStepTest {

    @Mock
    private TestSteps steps;

    @Test
    public void given_step_invocation() {
        given(() -> {
            steps.step1();
        });

        verify(steps).step1();

    }


    interface TestSteps {
        public void step1();
    }
}
