package com.codehackerr.simple.bdd;/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import org.junit.Test;
import org.junit.runner.RunWith;
import org.mockito.Mock;
import org.mockito.runners.MockitoJUnitRunner;

import static com.codehackerr.simple.bdd.SimpleBDD.given;
import static com.codehackerr.simple.bdd.SimpleBDD.then;
import static com.codehackerr.simple.bdd.SimpleBDD.when;
import static org.mockito.Mockito.verify;

@RunWith(MockitoJUnitRunner.class)
public class SimpleBDDStepTest {

    @Mock
    private TestSteps steps;

    @Test
    public void given_step_invocation() {
        given("Step 1", () -> {
            steps.step1();
        });

        verify(steps).step1();
    }

    @Test
    public void when_step_invocation() {
        when("Step 1", () -> {
            steps.step1();
        });

        verify(steps).step1();
    }

    @Test
    public void then_step_invocation() {
        then("Step 1", () -> {
            steps.step1();
        });

        verify(steps).step1();
    }


    interface TestSteps {
        public void step1();
    }
}
